import QRH.Detector.OptimizedMixedSaving
#print axioms OAI.SevenEighths.QRHProbeCentralExponent.adaptive_count_range
#print axioms OAI.SevenEighths.QRHProbeCentralExponent.balanced_mixed_margin
#print axioms OAI.SevenEighths.QRHProbeCentralExponent.balanced_mixed_saving
