import QRH.Energy.ReferenceLowBranchGeometry
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.slot_budgets_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.reflected_low_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.deleted_reference_cases_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.reflected_low_admissible_extended
