import QRH.Energy.LiveClippingDefect
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_slot_budgets_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_defect_le_width_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_balanced_long_nonneg_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_reflected_low_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_reflected_low_admissible_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_deleted_cases_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_fixed_slack_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_deleted_reference_cases_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.robust_deleted_reference_window_extended
#print axioms OAI.SevenEighths.CenteredMomentEnergyLiveClippingDefect.live_profiles_reference_window_extended
