import QRH.Detector.ExtendedFiniteProduct
#print axioms OAI.SevenEighths.QRHFiniteProduct.correction_lower_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.correction_ne_zero
#print axioms OAI.SevenEighths.QRHFiniteProduct.correction_inverse_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.marked_differentiableAt_w
#print axioms OAI.SevenEighths.QRHFiniteProduct.marked_differentiableAt_z
#print axioms OAI.SevenEighths.QRHFiniteProduct.local_analytic_w
#print axioms OAI.SevenEighths.QRHFiniteProduct.local_analytic_z
#print axioms OAI.SevenEighths.QRHFiniteProduct.marked_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.local_norm_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.selected_analytic_w
#print axioms OAI.SevenEighths.QRHFiniteProduct.selected_analytic_z
#print axioms OAI.SevenEighths.QRHFiniteProduct.slot_analytic_w
#print axioms OAI.SevenEighths.QRHFiniteProduct.slot_analytic_z
#print axioms OAI.SevenEighths.QRHFiniteProduct.selected_norm_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.slot_norm_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.global_norm_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.combined_slot_analytic_w
#print axioms OAI.SevenEighths.QRHFiniteProduct.combined_slot_analytic_z
#print axioms OAI.SevenEighths.QRHFiniteProduct.combined_slot_bound
#print axioms OAI.SevenEighths.QRHFiniteProduct.source_w_boundary
#print axioms OAI.SevenEighths.QRHFiniteProduct.source_z_boundary
#print axioms OAI.SevenEighths.QRHFiniteProduct.source_multiplier_differentiable_w
#print axioms OAI.SevenEighths.QRHFiniteProduct.source_multiplier_differentiable_z
#print axioms OAI.SevenEighths.QRHFiniteProduct.source_w_shift
#print axioms OAI.SevenEighths.QRHFiniteProduct.source_residue_z_shift
#print axioms OAI.SevenEighths.QRHFiniteProduct.slot_norm_bound_sharp
#print axioms OAI.SevenEighths.QRHFiniteProduct.combined_slot_bound_sharp
#print axioms OAI.SevenEighths.QRHFiniteProduct.fixed_source_boundaries
#print axioms OAI.SevenEighths.QRHFiniteProduct.fixed_source_ordered_boundaries
#print axioms OAI.SevenEighths.QRHFiniteProduct.uniform_closed_box_bound
